services:
  - type: web
    name: sportsstats-api
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

      # Firebase Configuration
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: AIzaSyAldoeFJwpEyiu_jistR3Aci9NtMq0QKis

      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: sportstatisti-7e594.firebaseapp.com

      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: sportstatisti-7e594

      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: sportstatisti-7e594.firebasestorage.app

      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: "948736641097"

      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: 1:948736641097:web:e382832db26708ce029798

      # NOWPayments Configuration
      - key: NOWPAYMENTS_API_KEY
        value: DQ1HPMB-6F94Y25-Q47KQMS-V90A5RQ

      - key: NOWPAYMENTS_IPN_SECRET
        value: HXDdgWaiedT5VJmxWLaoy/O7wl+YcEuv

      # JWT Secret (generate random 32+ character string)
      - key: JWT_SECRET
        value: sportsStatsAPI2024SecureJWTKeyForProductionUse32Plus

      # API URL (will be provided by Render after deployment)
      - key: NEXT_PUBLIC_API_URL
        sync: false  # Set to your Render app URL like https://sportsstats-api.onrender.com

    # Health check endpoint
    healthCheckPath: /api/health

    # Auto deploy from main branch
    autoDeploy: true

    # Domains (optional - add custom domain later)
    # domains:
    #   - sportsstats-api.com